import "./globals.css";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="h-full bg-black text-white">
            <body className="h-full">{children}</body>
        </html>
    );
}
