openapi: 3.0.3
info:
  title: Background Confidence Gate (Planning Contract)
  version: 0.1.0
paths:
  /interviews/{sessionId}/background/evaluate:
    post:
      summary: Submit candidate answer and update background confidence
      parameters:
        - in: path
          name: sessionId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
                metadata:
                  type: object
      responses:
        '200':
          description: Updated assessment state
          content:
            application/json:
              schema:
                type: object
                properties:
                  confidence:
                    type: number
                  perPillar:
                    type: object
                  shouldAdvance:
                    type: boolean
  /interviews/{sessionId}/background/debug:
    get:
      summary: Get current stage and confidence (DEBUG_MODE only)
      parameters:
        - in: path
          name: sessionId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Debug info
          content:
            application/json:
              schema:
                type: object
                properties:
                  stage:
                    type: string
                  confidence:
                    type: number
